# frozen_string_literal: true

require "json"
require "open3"
require "pathname"
require "tempfile"

module Picoruby::Cloudflare::Template
  # The Ruby/JS implementation stays in the optional mgem. This class owns only
  # generated Worker wiring and an effective Wrangler config beside the source.
  class PondroExport
    CONFIG_FILE = ".picoruby-cloudflare-wrangler.jsonc"
    HEADER = "// Generated by picoruby-cloudflare-template. Edit wrangler.jsonc and build_config.rb instead.\n"
    attr_reader :options, :config_path

    def initialize(options, root:, output:, wrangler:, environment:)
      @root, @output, @wrangler, @environment = root, output, wrangler, environment
      @config_path = File.join(root, CONFIG_FILE)
      @options = normalize(options) unless options.nil?
      if enabled? && File.dirname(wrangler) != root
        raise Error, "Pondro wrangler_config must be in project_root so relative paths and .dev.vars keep their meaning"
      end
    end

    def enabled?
      !@options.nil?
    end

    def plugin_options
      @options.slice("binding", "classes")
    end

    def validate_runtime!(gem_dir)
      return unless enabled?
      source = File.read(File.join(gem_dir, "templates/runtime/runtime.js"))
      unless source.match?(/\bexport\s+(?:async\s+)?function\s+dispatchEvent\b/)
        raise Error, "Pondro requires Worker ABI 9 with dispatchEvent; configure a compatible local Worker checkout or revision"
      end
    end

    def configuration
      return unless enabled?
      config = read_config
      selected = if @environment
        config.fetch("env", {})[@environment].tap do |env|
          raise Error, "Wrangler environment #{@environment} is not configured" unless env.is_a?(Hash)
        end
      else
        config
      end
      main = selected.fetch("main", config["main"])
      unless main.is_a?(String) && !main.empty? && File.file?(File.expand_path(main, @root))
        raise Error, "Pondro requires an existing Wrangler main entry"
      end
      entry = File.join(@output, "entry.js")
      raise Error, "Wrangler main must point to the source entry, not Pondro's generated entry.js" if File.expand_path(main, @root) == entry
      @main = File.expand_path(main, @root)
      generated_main = relative(entry)
      config["main"] = generated_main
      selected["main"] = generated_main if !selected.equal?(config) && selected.key?("main")
      add_binding(selected)
      add_migration(selected.key?("migrations") ? selected : config)
      config
    end

    def entry(_config)
      source = Pathname.new(@main).relative_path_from(Pathname.new(@output)).to_s
      source = "./#{source}" unless source.start_with?(".")
      <<~JS
        // Generated Pondro entry; the application's source entry remains intact.
        import { DurableObject } from "cloudflare:workers";
        import createPicoRuby from "./runtime/picoruby-worker.js";
        import wasm from "./runtime/picoruby-worker.wasm";
        import app from "./app.bin";
        import * as runtime from "./runtime/runtime.js";
        import { createPondroDurableObject } from "./runtime/plugins/pondro.js";
        export const #{@options.fetch("class_name")} = createPondroDurableObject({
          ...#{JSON.generate(plugin_options)}, DurableObject, runtime, createPicoRuby, wasm, app,
        });
        export * from #{source.to_json};
        export { default } from #{source.to_json};
      JS
    end

    def write_config(config)
      check_config_path!
      content = HEADER + JSON.pretty_generate(config) + "\n"
      return if File.file?(@config_path) && File.binread(@config_path) == content.b
      Tempfile.create(["pondro", ".jsonc"], @root) do |temp|
        temp.write(content)
        temp.close
        File.rename(temp.path, @config_path)
      end
    end

    def remove_config
      return unless File.exist?(@config_path) || File.symlink?(@config_path)
      check_config_path!
      File.unlink(@config_path)
    end

    private

    def read_config
      # Use the same JSONC dependency as the binding registry. Serialize only to
      # the generated config; comments and formatting in the source are retained.
      script = <<~JS
        const fs = require('node:fs');
        const {parse} = require('jsonc-parser');
        const errors = [];
        const data = parse(fs.readFileSync(process.argv[1], 'utf8'), errors, {allowTrailingComma:true});
        if (errors.length || !data || typeof data !== 'object' || Array.isArray(data)) throw new Error('Invalid Wrangler JSONC');
        process.stdout.write(JSON.stringify(data));
      JS
      output, status = Open3.capture2e("node", "-e", script, @wrangler, chdir: @root)
      raise Error, "Cannot read Wrangler JSONC; run npm install and check #{@wrangler}:\n#{output}" unless status.success?
      JSON.parse(output)
    end

    def normalize(value)
      raise Error, "pondro must be a Hash with binding and classes" unless value.is_a?(Hash)
      value = value.transform_keys(&:to_s)
      unknown = value.keys - %w[binding classes class_name migration_tag]
      raise Error, "Unknown Pondro options: #{unknown.join(', ')}" unless unknown.empty?
      options = { "binding" => "PONDRO", "class_name" => "PondroDurableObject", "migration_tag" => "pondro-v1" }.merge(value)
      unless options["binding"].is_a?(String) && options["binding"].match?(/\A[A-Za-z_][A-Za-z0-9_]{0,255}\z/)
        raise Error, "Invalid Pondro binding name"
      end
      unless options["class_name"].is_a?(String) && options["class_name"].match?(/\A[A-Z][A-Za-z0-9_]*\z/) && options["class_name"] != "PicoRubyDurableObject"
        raise Error, "Pondro class_name must be a JS export name distinct from PicoRubyDurableObject"
      end
      classes = options["classes"]
      unless classes.is_a?(Array) && !classes.empty? && classes.uniq.size == classes.size &&
          classes.all? { |name| name.is_a?(String) && !name.empty? && name.bytesize <= 256 }
        raise Error, "Pondro classes must be a nonempty array of unique class names of at most 256 bytes"
      end
      unless options["migration_tag"].is_a?(String) && options["migration_tag"].match?(/\A[A-Za-z0-9_.-]{1,128}\z/)
        raise Error, "Invalid Pondro migration_tag"
      end
      options
    end

    def relative(path)
      Pathname.new(path).relative_path_from(Pathname.new(@root)).to_s
    end

    def add_binding(config)
      objects = config["durable_objects"] ||= {}
      raise Error, "durable_objects must be an object" unless objects.is_a?(Hash)
      bindings = objects["bindings"] ||= []
      raise Error, "durable_objects.bindings must be an array of objects" unless bindings.is_a?(Array) && bindings.all? { _1.is_a?(Hash) }
      matches = bindings.select { _1["name"] == @options["binding"] }
      if matches.size > 1 || matches.any? { _1["class_name"] != @options["class_name"] || _1.key?("script_name") }
        raise Error, "Pondro binding #{@options['binding']} conflicts with an existing Durable Object binding"
      end
      bindings << { "name" => @options["binding"], "class_name" => @options["class_name"] } if matches.empty?
    end

    def add_migration(config)
      migrations = config["migrations"] ||= []
      raise Error, "migrations must be an array of objects" unless migrations.is_a?(Array) && migrations.all? { _1.is_a?(Hash) }
      name = @options.fetch("class_name")
      return if migrations.any? { Array(_1["new_sqlite_classes"]).include?(name) }
      if migrations.any? { Array(_1["new_classes"]).include?(name) }
        raise Error, "Pondro class #{name} already has a non-SQLite migration"
      end
      tag = @options.fetch("migration_tag")
      raise Error, "Pondro migration tag #{tag} conflicts; choose migration_tag explicitly" if migrations.any? { _1["tag"] == tag }
      migrations << { "tag" => tag, "new_sqlite_classes" => [name] }
    end

    def check_config_path!
      if File.symlink?(@config_path) || (File.exist?(@config_path) &&
          (!File.file?(@config_path) || !File.binread(@config_path).start_with?(HEADER)))
        raise Error, "Refusing to overwrite a non-generated file: #{@config_path}"
      end
    end
  end
end
